
#Ticket states
TKT_NEW = 0
TKT_NEEDS_CLARIFICATION = 1
TKT_QUOTED = 2
TKT_NEEDS_REVIEW = 3 #could not quote!
TKT_REJECTED = 4
TKT_ACCEPTED = 5
TKT_ASSIGNED = 6
TKT_IN_PROGRESS = 7
TKT_DELIVERED_PENDING_PAYMENT = 8
TKT_DELIVERED = 9
TKT_CLOSED = 10
TKT_CANCELLED = 11

# state rules
CLAIMABLE_STATES = {TKT_ACCEPTED}
WORKABLE_STATES  = {TKT_ASSIGNED, TKT_IN_PROGRESS}
LOCKED_STATES    = {TKT_DELIVERED_PENDING_PAYMENT, TKT_DELIVERED, TKT_CLOSED, TKT_CANCELLED}
QUESTION_EDITABLE_STATES = {TKT_NEEDS_CLARIFICATION, TKT_NEEDS_REVIEW, TKT_QUOTED, TKT_REJECTED}

ALL_STATES = [
    TKT_NEW, TKT_NEEDS_CLARIFICATION, TKT_QUOTED, TKT_NEEDS_REVIEW, TKT_REJECTED,
    TKT_ACCEPTED, TKT_ASSIGNED, TKT_IN_PROGRESS,
    TKT_DELIVERED_PENDING_PAYMENT, TKT_DELIVERED,
    TKT_CLOSED, TKT_CANCELLED,
]
